---
title: "Modulo3 guia de Ejercicios"
author: "julio"
date: "25/11/2020"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, Warning = FALSE, message = FALSE)
```

```{r}
library(dplyr)
```

```{r}
wbData1 <- readRDS("datos/wbData2019.rds")


```

## pregunta 1


```{r}
wbData2 <- wbData1 %>% rename(population = SP.POP.TOTL,
                              lifeExpectancy = SP.DYN.LE00.IN,
                              gdppc = NY.GDP.PCAP.PP.CD,
                              gini = SI.POV.GINI)

```


## pregunta 2


```{r}
wbData2 <- wbData1 %>% arrange(country,year)
```


## pregunta 3


```{r}
wbData2 <- wbData1 %>% mutate(region = recode(region, 
                                              "East Asia & Pacific" = "Este Asiatico y Pacifico", 
                                              "Europe & Central Asia" = "Europa y Asia Central", 
                                              "Latin American & Caribbean" = "America Latina y el Caribe", 
                                              "Middle East & North Africa" = "Medio Oriente y Norte de Africa",
                                              "North America" = "Norteamerica", 
                                              "South Asia" = "Asia del Sur", 
                                            "Sub-Sahara Africa" =  "Africa Subsahariana"))
``` 
 
## pregunta 4
 
```{r}

#table(wbData2$region)

regiones <- wbData2 %>% 
            distinct(region) %>% 
            count()


regiones <- wbData2 %>% 
            group_by(region) %>% 
            count()


wbData3 <- wbData2 %>% 
           filter(region != "Aggregates")



```

```{r}
z  <- wbData2 %>% filter(!is.na(region))

```


```{r}
zz <- wbData3 %>% distinct(country) %>% 
            count()
```

```{r}
zzz <- wbData3 %>% group_by(region) %>% 
            distinct(country) %>% 
            count()

```



```{r}

library(janitor)
library(kableExtra)

wbData3 %>% group_by(region) %>% 
            distinct(country) %>% 
            count() %>% 
            ungroup() %>% 
            mutate(perc = (n/sum(n))*100) %>% 
            adorn_totals("row") %>% 
            kbl(booktabs = T,
                col.names = c("region", "Numero paises", "%"),
                linesep = '',
                digits = 1) %>% 
            kable_styling(latex_options = c("striped"))


```



## pregunta 5

```{r}

wbData3 %>% 
  filter(year == 2019) %>%
  select(country, population) %>% 
  arrange(desc(population)) %>% 
  slice_head(n = 5) %>% 
  kbl(booktabs = T,
      col.names = c("pais", "population"),
      linesep = '',
      digits = 1) %>% 
  kable_styling(latex_options = c("striped"))
  

```



## pregunta 6


```{r}
wbData3 %>% 
  group_by(country) %>% 
  filter(year >= 2018, year <= 2019) %>%
  mutate(crecimiento = round((population - lag(population))/(lag(population))*100)) %>% 
  select(country,crecimiento) %>% 
  arrange(desc(crecimiento)) %>% 
  slice_head(n = 10)
 
```

## pregunta 7

```{r}
wbData3 %>% 
  filter(year == 2019) %>%
  select(country,gdppc) %>% 
  arrange(gdppc) %>% 
  slice_head(n = 10)
```


## pregunta 8

```{r}
wbData3 %>% 
  filter(year == 2019) %>%
  select(country,gdppc) %>% 
  arrange(gdppc) %>% 
  slice_head(n = 10)
```









