---
title: "DB PERSONAS"
author: "julio"
date: "23/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## BASE DE DATOS PERSONAS


## LECUTRA DE DATOS

```{r}
#--------------------
# ESTA BASE ES LA DE PERSONAS CON TODOS SUS DATOS NUMERICOS

library(readr)
# VERIFICA QUE TIPO DE DATO ES LA COLUMNA A ANLIZAR
# LO GUARDA EN LA VARIABLE COL
col <- spec_csv("datos/PERSONAS_v4.csv")

# COPIE Y PEGE EL VECTOR COL Y LO VOLVI ASIGNAR A COL .. PORQUE?
# CUANDO GENERO EL SPEC_CSV MUCHAS VECES DEJA COLUMNAS SIN TIPO Y AL MOMENTO DE CARGARLAS DA ERROR
# POR ESO REASIGNAS UN NUEVO TIPO A ESAS COLUMNAS QUE NO SE LES ASIGNO NINGUN TIPO
col <- cols(
  DOMINIO = col_double(),
  AREA = col_double(),
  UPM = col_double(),
  FACTOR = col_double(),
  NUM_HOGAR = col_double(),
  ID = col_double(),
  PPA02 = col_double(),
  PPA03 = col_double(),
  PPA04A = col_double(),
  PPA04B = col_double(),
  PPA04C = col_double(),
  PPA05 = col_double(),
  PPA06 = col_double(),
  PPA07 = col_double(),
  PPA08 = col_double(),
  PPA09 = col_double(),
  PPA10A = col_double(),
  PPA10B = col_double(),
  PPA11 = col_double(),
  PPA12 = col_double(),
  P03A01 = col_double(),
  P03A02 = col_double(),
  P03A03 = col_double(),
  P03A04A = col_double(),
  P03A04B = col_double(),
  P03A05A = col_double(),
  P03A05B = col_double(),
  P03A06 = col_double(),
  P03B01 = col_double(),
  P03B02 = col_double(),
  P03B03 = col_double(),
  P03B04 = col_double(),
  P03B05 = col_double(),
  P03C01 = col_double(),
  P03C02 = col_double(),
  P03C03 = col_double(),
  P03C04 = col_double(),
  P03C05 = col_double(),
  P03C06 = col_double(),
  P03D01 = col_double(),
  P03D02A = col_double(),
  P03D02B = col_double(),
  P03D03 = col_double(),
  P03D04 = col_double(),
  P03D05 = col_double(),
  P03D06 = col_double(),
  P03D07A = col_double(),
  P03D07B = col_double(),
  P03D07C = col_double(),
  P03D07D = col_double(),
  P03D07E = col_double(),
  P03D08 = col_double(),
  P04A01 = col_double(),
  P04A02 = col_double(),
  P04A03 = col_double(),
  P04A04 = col_double(),
  P04A05 = col_double(),
  P04A06 = col_double(),
  P04A07 = col_double(),
  P04A08 = col_double(),
  P04A09 = col_double(),
  P04B01 = col_double(),
  P04B02 = col_double(),
  P04B03 = col_double(),
  P04B04 = col_double(),
  P04B05 = col_double(),
  P04C01 = col_double(),
  P04C02B_2D = col_double(),
  P04C02B_1D = col_double(),
  P04C04B_2D = col_double(),
  P04C04B_1D = col_double(),
  P04C05 = col_double(),
  P04C06 = col_double(),
  P04C07 = col_double(),
  P04C08A = col_double(),
  P04C08B = col_double(),
  P04C08C = col_double(),
  P04C09A = col_double(),
  P04C09B = col_double(),
  P04C10 = col_double(),
  P04C11A = col_double(),
  P04C11B = col_double(),
  P04C11C = col_double(),
  P04C12A = col_double(),
  P04C12B = col_double(),
  P04C13A = col_double(),
  P04C13B = col_double(),
  P04C14A = col_double(),
  P04C14B = col_double(),
  P04C15A = col_double(),
  P04C15B = col_double(),
  P04C16A = col_double(),
  P04C16B = col_double(),
  P04C17A = col_double(),
  P04C17B = col_double(),
  P04C18A = col_double(),
  P04C18B = col_double(),
  P04C19A = col_double(),
  P04C19B = col_double(),
  P04C20A = col_double(),
  P04C20B = col_double(),
  P04C21A = col_double(),
  P04C21B = col_double(),
  P04C22 = col_double(),
  P04C23 = col_double(),
  P04C24A = col_double(),
  P04C24B = col_double(),
  P04C25A = col_double(),
  P04C25B = col_double(),
  P04C26A = col_double(),
  P04C26B = col_double(),
  P04C27 = col_double(),
  P04C28A = col_double(),
  P04C28B = col_double(),
  P04C28C = col_double(),
  P04C28D = col_double(),
  P04C28E = col_double(),
  P04C28F = col_double(),
  P04C28G = col_double(),
  P04C29 = col_double(),
  P04C30 = col_double(),
  P04C31A = col_double(),
  P04C31B = col_double(),
  P04C32 = col_double(),
  P04C33 = col_double(),
  P04C34A = col_double(),
  P04C34B = col_double(),
  P04C34C = col_double(),
  P04C34D = col_double(),
  P04C34E = col_double(),
  P04C35A = col_double(),
  P04C35B = col_double(),
  P04C35C = col_double(),
  P04C35D = col_double(),
  P04C35E = col_double(),
  P04C35F = col_double(),
  P04C35G = col_double(),
  P04C36 = col_double(),
  P04C37 = col_double(),
  P04C38 = col_double(),
  P04C39 = col_double(),
  P04D01 = col_double(),
  P04D02B_2D = col_double(),
  P04D02B_1D = col_double(),
  P04D04B_2D = col_double(),
  P04D04B_1D = col_double(),
  P04D05 = col_double(),
  P04D06 = col_double(),
  P04D07A = col_double(),
  P04D07B = col_double(),
  P04D08A = col_double(),
  P04D08B = col_double(),
  P04D09A = col_double(),
  P04D09B = col_double(),
  P04D10A = col_double(),
  P04D10B = col_double(),
  P04D11A = col_double(),
  P04D11B = col_double(),
  P04D12 = col_double(),
  P04D13 = col_double(),
  P04D14A = col_double(),
  P04D14B = col_double(),
  P04D15 = col_double(),
  P04D16 = col_double(),
  P04D17A = col_double(),
  P04D17B = col_double(),
  P04E01 = col_double(),
  P04E02A = col_double(),
  P04E02B = col_double(),
  P04E02C = col_double(),
  P04E03 = col_double(),
  P04E04 = col_double(),
  P04E05 = col_double(),
  P04E06 = col_double(),
  P04E07A = col_double(),
  P04E08A = col_double(),
  P04E08B = col_double(),
  P04E09 = col_double(),
  P04E10 = col_double(),
  P04F01 = col_double(),
  P04F02B_2D = col_double(),
  P04F02B_1D = col_double(),
  P04F03 = col_double(),
  P04F04 = col_double(),
  P04F05A = col_double(),
  P04F05B = col_double(),
  P04F05C = col_double(),
  P04F05D = col_double(),
  P04F05E = col_double(),
  P04F05F = col_double(),
  P04F05G = col_double(),
  P04F06 = col_double(),
  P04F07B_2D = col_double(),
  P04F07B_1D = col_double(),
  P04F08 = col_double(),
  P04F09B_2D = col_double(),
  P04F09B_1D = col_double(),
  P04F10 = col_double(),
  P04F11 = col_double(),
  P04F12 = col_double(),
  P04F13 = col_double(),
  P04G01 = col_double(),
  P04G02 = col_double(),
  P04G03 = col_double(),
  P04G04 = col_double(),
  P04G05A = col_double(),
  P04G05B = col_double(),
  P04G05C = col_double(),
  P04G05D = col_double(),
  P04G05E = col_double(),
  P04G05F = col_double(),
  P04G05G = col_double(),
  P04G05H = col_double(),
  P04G05I = col_double(),
  P05A01A = col_double(),
  P05A01B = col_double(),
  P05A02A = col_double(),
  P05A02B = col_double(),
  P05A03A = col_double(),
  P05A03B = col_double(),
  P05A04A = col_double(),
  P05A04B = col_double(),
  P05A05A = col_double(),
  P05A05B = col_double(),
  P05A06A = col_double(),
  P05A06B = col_double(),
  P05A07A = col_double(),
  P05A07B = col_double(),
  P05A08A = col_double(),
  P05A08B = col_double(),
  P05A09A = col_double(),
  P05A09B = col_double(),
  P05A10A = col_double(),
  P05A10B = col_double(),
  P05A11A = col_double(),
  P05A11B = col_double(),
  P05A12A = col_double(),
  P05A12B = col_double(),
  P05A13A = col_double(),
  P05A13B = col_double(),
  P05A14A = col_double(),
  P05A14B = col_double(),
  P05A15A = col_double(),
  P05A15B = col_double(),
  P05A16A = col_double(),
  P05A16B = col_double(),
  P05A17A = col_double(),
  P05A17B = col_double(),
  P05A18A = col_double(),
  P05A18B = col_double(),
  P05A19A = col_double(),
  P05A19B = col_double(),
  P05A20A = col_double(),
  P05A20B = col_double(),
  P05A21A = col_double(),
  P05A21B = col_double(),
  etnicidad = col_double(),
  PET = col_double(),
  PEA = col_double(),
  OCUPADOS = col_double(),
  DESOCUPADOS = col_double(),
  SUBVISIBLES = col_double(),
  INACTIVOS = col_double(),
  FORMAL_INFORMAL = col_double()
)

# CARGO LA BASE DE DATOS PERSONAS Y LE PASO COL_TYPES = COL
# QUE ESTO LE ASIGNA QUE TIPO DE COLUMNA ES CADA COLUMNA CARGADA DE LA BASE DE PERSONAS
PERSONAS <- read_csv("datos/PERSONAS_v4.csv")
PERSONAS

# SI SALE UN ERROR AL MOMENTO DE CARGARLAS SE PUEDEN VER CON "PROBLEMS"
# LE ASIGNO A LA VARIABLE PROBLEMAS LOS CASOS MALOS
# SI ESTA VACIA ESA VARIABLE ES QUE TODO SE CARGO CORRECTAMENTE
PROBLEMAS <- problems(PERSONAS)

```


```{r}
#--------
# ESTA BASE ES LA DE PERSONAS PERO CON SUS ETIQUETAS COMO VALORES

library(readr)

# VERIFICA QUE TIPO DE DATO ES LA COLUMNA A ANLIZAR
# LO GUARDA EN LA VARIABLE COL
col2 <- spec_csv("datos/PERSONAS.csv")

# COPIE Y PEGE EL VECTOR COL Y LO VOLVI ASIGNAR A COL .. PORQUE?
# CUANDO GENERO EL SPEC_CSV MUCHAS VECES DEJA COLUMNAS SIN TIPO Y AL MOMENTO DE CARGARLAS DA ERROR
# POR ESO REASIGNAS UN NUEVO TIPO A ESAS COLUMNAS QUE NO SE LES ASIGNO NINGUN TIPO
# COMO HAY VARIABLES TEXTO SE USA CHARACTER Y SI ES NUMERO DOUBLE
col2 <- cols(
  DOMINIO = col_character(),
  AREA = col_character(),
  UPM = col_double(),
  FACTOR = col_double(),
  NUM_HOGAR = col_double(),
  ID = col_double(),
  PPA02 = col_character(),
  PPA03 = col_double(),
  PPA04A = col_double(),
  PPA04B = col_character(),
  PPA04C = col_double(),
  PPA05 = col_character(),
  PPA06 = col_character(),
  PPA07 = col_character(),
  PPA08 = col_character(),
  PPA09 = col_character(),
  PPA10A = col_character(),
  PPA10B = col_double(),
  PPA11 = col_double(),
  PPA12 = col_character(),
  P03A01 = col_character(),
  P03A02 = col_character(),
  P03A03 = col_character(),
  P03A04A = col_character(),
  P03A04B = col_double(),
  P03A05A = col_character(),
  P03A05B = col_double(),
  P03A06 = col_character(),
  P03B01 = col_character(),
  P03B02 = col_character(),
  P03B03 = col_character(),
  P03B04 = col_character(),
  P03B05 = col_character(),
  P03C01 = col_character(),
  P03C02 = col_character(),
  P03C03 = col_character(),
  P03C04 = col_character(),
  P03C05 = col_character(),
  P03C06 = col_character(),
  P03D01 = col_character(),
  P03D02A = col_character(),
  P03D02B = col_double(),
  P03D03 = col_character(),
  P03D04 = col_character(),
  P03D05 = col_character(),
  P03D06 = col_character(),
  P03D07A = col_character(),
  P03D07B = col_character(),
  P03D07C = col_character(),
  P03D07D = col_character(),
  P03D07E = col_character(),
  P03D08 = col_character(),
  P04A01 = col_double(),
  P04A02 = col_character(),
  P04A03 = col_character(),
  P04A04 = col_character(),
  P04A05 = col_character(),
  P04A06 = col_character(),
  P04A07 = col_character(),
  P04A08 = col_character(),
  P04A09 = col_character(),
  P04B01 = col_character(),
  P04B02 = col_character(),
  P04B03 = col_character(),
  P04B04 = col_character(),
  P04B05 = col_character(),
  P04C01 = col_character(),
  P04C02B_2D = col_character(),
  P04C02B_1D = col_character(),
  P04C04B_2D = col_character(),
  P04C04B_1D = col_character(),
  P04C05 = col_double(),
  P04C06 = col_character(),
  P04C07 = col_character(),
  P04C08A = col_character(),
  P04C08B = col_double(),
  P04C08C = col_double(),
  P04C09A = col_character(),
  P04C09B = col_character(),
  P04C10 = col_double(),
  P04C11A = col_character(),
  P04C11B = col_double(),
  P04C11C = col_double(),
  P04C12A = col_character(),
  P04C12B = col_double(),
  P04C13A = col_character(),
  P04C13B = col_double(),
  P04C14A = col_character(),
  P04C14B = col_double(),
  P04C15A = col_character(),
  P04C15B = col_double(),
  P04C16A = col_character(),
  P04C16B = col_double(),
  P04C17A = col_character(),
  P04C17B = col_double(),
  P04C18A = col_character(),
  P04C18B = col_double(),
  P04C19A = col_character(),
  P04C19B = col_double(),
  P04C20A = col_character(),
  P04C20B = col_double(),
  P04C21A = col_character(),
  P04C21B = col_double(),
  P04C22 = col_double(),
  P04C23 = col_double(),
  P04C24A = col_character(),
  P04C24B = col_double(),
  P04C25A = col_character(),
  P04C25B = col_double(),
  P04C26A = col_double(),
  P04C26B = col_character(),
  P04C27 = col_character(),
  P04C28A = col_double(),
  P04C28B = col_double(),
  P04C28C = col_double(),
  P04C28D = col_double(),
  P04C28E = col_double(),
  P04C28F = col_double(),
  P04C28G = col_double(),
  P04C29 = col_character(),
  P04C30 = col_double(),
  P04C31A = col_double(),
  P04C31B = col_double(),
  P04C32 = col_character(),
  P04C33 = col_character(),
  P04C34A = col_character(),
  P04C34B = col_character(),
  P04C34C = col_character(),
  P04C34D = col_character(),
  P04C34E = col_character(),
  P04C35A = col_character(),
  P04C35B = col_character(),
  P04C35C = col_double(),
  P04C35D = col_character(),
  P04C35E = col_character(),
  P04C35F = col_character(),
  P04C35G = col_character(),
  P04C36 = col_character(),
  P04C37 = col_character(),
  P04C38 = col_character(),
  P04C39 = col_character(),
  P04D01 = col_character(),
  P04D02B_2D = col_double(),
  P04D02B_1D = col_double(),
  P04D04B_2D = col_character(),
  P04D04B_1D = col_character(),
  P04D05 = col_character(),
  P04D06 = col_double(),
  P04D07A = col_character(),
  P04D07B = col_double(),
  P04D08A = col_character(),
  P04D08B = col_double(),
  P04D09A = col_character(),
  P04D09B = col_double(),
  P04D10A = col_character(),
  P04D10B = col_double(),
  P04D11A = col_character(),
  P04D11B = col_double(),
  P04D12 = col_double(),
  P04D13 = col_double(),
  P04D14A = col_character(),
  P04D14B = col_double(),
  P04D15 = col_double(),
  P04D16 = col_double(),
  P04D17A = col_double(),
  P04D17B = col_double(),
  P04E01 = col_character(),
  P04E02A = col_double(),
  P04E02B = col_double(),
  P04E02C = col_double(),
  P04E03 = col_double(),
  P04E04 = col_character(),
  P04E05 = col_character(),
  P04E06 = col_character(),
  P04E07A = col_character(),
  P04E08A = col_character(),
  P04E08B = col_double(),
  P04E09 = col_character(),
  P04E10 = col_character(),
  P04F01 = col_character(),
  P04F02B_2D = col_character(),
  P04F02B_1D = col_character(),
  P04F03 = col_character(),
  P04F04 = col_character(),
  P04F05A = col_double(),
  P04F05B = col_double(),
  P04F05C = col_double(),
  P04F05D = col_double(),
  P04F05E = col_double(),
  P04F05F = col_double(),
  P04F05G = col_double(),
  P04F06 = col_character(),
  P04F07B_2D = col_character(),
  P04F07B_1D = col_character(),
  P04F08 = col_character(),
  P04F09B_2D = col_character(),
  P04F09B_1D = col_character(),
  P04F10 = col_character(),
  P04F11 = col_double(),
  P04F12 = col_character(),
  P04F13 = col_double(),
  P04G01 = col_character(),
  P04G02 = col_character(),
  P04G03 = col_character(),
  P04G04 = col_character(),
  P04G05A = col_character(),
  P04G05B = col_character(),
  P04G05C = col_character(),
  P04G05D = col_character(),
  P04G05E = col_character(),
  P04G05F = col_character(),
  P04G05G = col_character(),
  P04G05H = col_character(),
  P04G05I = col_character(),
  P05A01A = col_character(),
  P05A01B = col_double(),
  P05A02A = col_character(),
  P05A02B = col_double(),
  P05A03A = col_character(),
  P05A03B = col_double(),
  P05A04A = col_character(),
  P05A04B = col_double(),
  P05A05A = col_character(),
  P05A05B = col_double(),
  P05A06A = col_character(),
  P05A06B = col_double(),
  P05A07A = col_character(),
  P05A07B = col_double(),
  P05A08A = col_character(),
  P05A08B = col_double(),
  P05A09A = col_character(),
  P05A09B = col_double(),
  P05A10A = col_character(),
  P05A10B = col_double(),
  P05A11A = col_character(),
  P05A11B = col_double(),
  P05A12A = col_character(),
  P05A12B = col_double(),
  P05A13A = col_character(),
  P05A13B = col_double(),
  P05A14A = col_character(),
  P05A14B = col_double(),
  P05A15A = col_character(),
  P05A15B = col_double(),
  P05A16A = col_character(),
  P05A16B = col_double(),
  P05A17A = col_double(),
  P05A17B = col_double(),
  P05A18A = col_double(),
  P05A18B = col_double(),
  P05A19A = col_character(),
  P05A19B = col_double(),
  P05A20A = col_character(),
  P05A20B = col_double(),
  P05A21A = col_character(),
  P05A21B = col_double(),
  etnicidad = col_character(),
  PET = col_character(),
  PEA = col_character(),
  OCUPADOS = col_character(),
  DESOCUPADOS = col_character(),
  SUBVISIBLES = col_double(),
  INACTIVOS = col_double(),
  FORMAL_INFORMAL = col_character()
)

# CARGO LA BASE DE DATOS PERSONAS Y LE PASO COL_TYPES = COL
# QUE ESTO LE ASIGNA QUE TIPO DE COLUMNA ES CADA COLUMNA CARGADA DE LA BASE DE PERSONAS
PERSONAS2 <- read_csv("datos/PERSONAS.csv")

# SI SALE UN ERROR AL MOMENTO DE CARGARLAS SE PUEDEN VER CON "PROBLEMS"
# LE ASIGNO A LA VARIABLE PROBLEMAS LOS CASOS MALOS
# SI ESTA VACIA ESA VARIABLE ES QUE TODO SE CARGO CORRECTAMENTE
PROBLEMAS2 <- problems(PERSONAS2)

```

```{r echo = TRUE}
#-------------
library(dplyr)

#RENOMBRAR VARIABLES

PERSONAS2 <- PERSONAS2 %>% rename(SEXO=PPA02, EDAD=PPA03, DIA=PPA04A, MES=PPA04B, ANIO=PPA04C, PARENTESCO = PPA05,
                                PUEBLOS=PPA06,LINGUISTICA=PPA07, IDIOMA =PPA08, ESTADO_CIVIL =PPA09,
                                MADRE_EN_HOGAR=PPA10A, COD_MADRE=PPA10B, TOTAL_HIJOS = PPA11, 
                                RESULTADO_ENTREVISTA = PPA12, OCUPACION = P04C02B_2D, ACTIVIDAD_ECONOMICA= P04C04B_2D,
                                INGRESOS = P04C10, AFILIADO_IGSS = P04C25A, LUGAR_TRABAJO = P03B01,
                                REMESAS = P05A17A, ACTIVIDAD_PRINCIPAL = P04A02)

PERSONAS2 <- PERSONAS2 %>% rename(ACTIVIDAD_PRINCIPAL = P04A02)

#-------------
#MANIPULACION DE DATOS

PERSONAS_OCUPADOS <-PERSONAS2 %>%
                    select(OCUPADOS)


table(PERSONAS$PEA)

table(PERSONAS$ACTIVIDAD_PRINCIPAL)

#OCUPADOS
table(PERSONAS$OCUPADOS)

#DESOCUPADOS
table(PERSONAS$DESOCUPADOS)



cousulta <- PERSONAS %>% group_by(PEA) %>% 
            count(wt = FACTOR)

cousulta2 <- PERSONAS %>% group_by(OCUPADOS) %>% 
            count(wt = FACTOR)

cousulta3 <- PERSONAS %>% group_by(DESOCUPADOS) %>% 
            count(wt = FACTOR)


t1 <- PERSONAS %>% 
        group_by(ACTIVIDAD_PRINCIPAL) %>% 
        count(name="total")


t1_1 <- PERSONAS_60 %>% 
        group_by(ACTIVIDAD_PRINCIPAL) 


t2 <- PERSONAS_60 %>% 
        filter(EDAD >=60) %>% 
        group_by(SEXO) %>% 
        count(name="total")

t3 <- PERSONAS_60 %>% 
        group_by(PUEBLOS) %>% 
        count(name="total")

t4 <- PERSONAS_60 %>% 
        group_by(PUEBLOS) %>% 
        count(name="total") 

t5 <- PERSONAS_60 %>% 
        group_by(OCUPACION) %>% 
        count(name="total") 

t6 <- PERSONAS_60 %>% 
        group_by(ACTIVIDAD_ECONOMICA) %>% 
        count(name="total") 

t7 <- PERSONAS_60 %>% 
        group_by(INGRESOS) %>% 
        count(name="total") 

t8 <- PERSONAS_60 %>% 
        group_by(AFILIADO_IGSS) %>% 
        count(name="total") 

t9 <- PERSONAS_60 %>% 
        group_by(LUGAR_TRABAJO) %>% 
        count(name="total") 

t10 <- PERSONAS_60 %>% 
        group_by(REMESAS) %>% 
        count(name="total") 

t11 <- PERSONAS_60 %>% 
        group_by(REMESAS) %>% 
        count(name="total") 




```



